### ISSUE TITLE
Update race winning strategy

### ISSUE THREAD

**Issue by Corpelijn** [Corpelijn/DankTimesBot-Plugin-HorseRaces#13]

**Comment by Agadar** [comment]
Make doping more significant as there's a risk attached and currently it feels like it does barely anything (if at all) for win chances.

Exclude players that haven't scored in a while / since the last nightly reset unless they're actively betting in the current race.

Make current points on leaderboard a non-factor because why should the rich get richer? We have real life for that already.

**Comment by Corpelijn** [comment]
@Agadar But removing the points of the leaderboard as a factor also means someone with a lot of points can dope into oblivion.

**Comment by Agadar** [comment]
No because they will kill their horse if they dope too much, correct?

**Comment by Corpelijn** [comment]
Currently that is depending on the user' score

**Comment by Agadar** [comment]
Maybe make it depend on the 1st place price or some other value then.
